language: node_js
node_js:
  - "stable"

deploy:
  provider: pages
  strategy: git
  cleanup: false
  token: $github_token          
  local_dir: build
  target_branch: gh-pages      
    branch: main
