name: CI (lab04-only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"     # istersen "20"

      - name: Install deps (lab04)
        run: npm ci || npm i
        working-directory: lab04

      - name: Run tests (lab04)
        run: npm test
        working-directory: lab04

      - name: Inject build timestamp into index.html
        run: |
          ts="$(date +"%Y-%m-%d %H:%M:%S")"
          perl -0777 -pe "s#</body>#<p style='font-family: system-ui; padding:0 40px;'>Build time (runner): <strong>${ts}</strong></p></body>#s" \
            lab04/index.html > /tmp/index.html && mv /tmp/index.html lab04/index.html

      - name: Upload Pages artifact (publish lab04/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./lab04

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
