name: CI
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "The branch is ${{ github.ref }} and repo is ${{ github.repository }}."
      - run: ls ${{ github.workspace }}
